FAST: Fix clang build breakage
Fixes the following clang complaints:

  CC       lib/proto/fast_message.o
lib/proto/fast_message.c:565:4: error: cast from 'char *' to 'u64 *' (aka
      'unsigned long long *') increases required alignment from 1 to 4
      [-Werror,-Wcast-align]
                *(u64 *)(field->string_value + len) = 0;
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lib/proto/fast_message.c:617:5: error: cast from 'char *' to 'u64 *' (aka
      'unsigned long long *') increases required alignment from 1 to 4
      [-Werror,-Wcast-align]
                        *(u64 *)(field->string_value + len) = 0;
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Marat Stanichenko <mstanichenko@gmail.com>
Signed-off-by: Pekka Enberg <penberg@kernel.org>